version: '2.1'

services:

  sleepypi:
    build: './sleepypi'
    labels:
      io.resin.features.dbus: '1'
      io.resin.features.supervisor-api: '1'
      io.balena.features.kernel-modules: '1'
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    cap_add:
      - SYS_RAWIO
    privileged: 'true'
    restart: 'always'
